// mockReminders.js
// Drop this anywhere and import MOCK_OVERDUE / MOCK_TODAY into your page for testing

const now = new Date();
const hrsAgo = (h) => new Date(now - h * 3600000).toISOString();
const hrsFrom = (h) => new Date(now.getTime() + h * 3600000).toISOString();
const daysAgo = (d) => new Date(now - d * 86400000).toISOString();

export const MOCK_OVERDUE = [
  {
    id: "r-001",
    title: "Call Sanjay about the GST meeting",
    description:
      "Need to confirm the new GST rates and whether the Google Meet is still on for Friday.",
    due_at: hrsAgo(3),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: false,
    recurrence_type: null,
    recurrence_every: null,
    bucket: { name: "Work", icon: "briefcase" },
    tags: [
      { id: "t1", name: "Call", color: "#3b82f6" },
      { id: "t2", name: "Urgent", color: "#ef4444" },
      { id: "t3", name: "Follow Up", color: "#f59e0b" },
    ],
    parent: null,
    children: [],
  },
  {
    id: "r-002",
    title: "Submit Q1 expense report",
    description:
      "Finance team needs all receipts attached. Ask Priya for the template.",
    due_at: daysAgo(2),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: false,
    recurrence_type: null,
    recurrence_every: null,
    bucket: { name: "Finance", icon: "wallet" },
    tags: [
      { id: "t4", name: "Email", color: "#8b5cf6" },
      { id: "t5", name: "Review", color: "#06b6d4" },
    ],
    parent: null,
    children: [],
  },
  {
    id: "r-003",
    title: "Weekly team standup notes",
    description: null,
    due_at: hrsAgo(26),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: true,
    recurrence_type: "WEEKLY",
    recurrence_every: 1,
    bucket: { name: "Work", icon: "briefcase" },
    tags: [{ id: "t6", name: "Meeting", color: "#10b981" }],
    parent: null,
    children: [{ id: "r-003-a" }, { id: "r-003-b" }],
  },
  {
    id: "r-004",
    title: "Renew gym membership",
    description: "Expires this month. Check if the annual plan is cheaper.",
    due_at: daysAgo(5),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: false,
    recurrence_type: null,
    recurrence_every: null,
    bucket: { name: "Health", icon: "heart" },
    tags: [{ id: "t7", name: "Personal", color: "#f97316" }],
    parent: null,
    children: [],
  },
];

export const MOCK_TODAY = [
  {
    id: "r-005",
    title: "Review Figma designs for the new dashboard",
    description:
      "Deepak shared the updated mockups last night. Leave comments before EOD.",
    due_at: hrsFrom(2),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: false,
    recurrence_type: null,
    recurrence_every: null,
    bucket: { name: "Work", icon: "briefcase" },
    tags: [
      { id: "t8", name: "Review", color: "#06b6d4" },
      { id: "t9", name: "Design", color: "#8b5cf6" },
      { id: "t10", name: "Urgent", color: "#ef4444" },
    ],
    parent: null,
    children: [],
  },
  {
    id: "r-006",
    title: "Send invoice #1042 to Meera Textiles",
    description: null,
    due_at: hrsFrom(0.5),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: false,
    recurrence_type: null,
    recurrence_every: null,
    bucket: { name: "Finance", icon: "wallet" },
    tags: [
      { id: "t11", name: "Email", color: "#8b5cf6" },
      { id: "t12", name: "Client", color: "#3b82f6" },
    ],
    parent: null,
    children: [],
  },
  {
    id: "r-007",
    title: "Take evening medication",
    description: "Vitamin D + Iron. Don't skip.",
    due_at: hrsFrom(5),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: true,
    recurrence_type: "DAILY",
    recurrence_every: 1,
    bucket: { name: "Health", icon: "heart" },
    tags: [],
    parent: null,
    children: [],
  },
  {
    id: "r-008",
    title: "Call mom",
    description: "Her birthday is coming up next week — ask what she wants.",
    due_at: hrsFrom(3),
    completed_at: null,
    snoozed_until: null,
    status: "PENDING",
    is_recurring: false,
    recurrence_type: null,
    recurrence_every: null,
    bucket: { name: "Family", icon: "home" },
    tags: [
      { id: "t13", name: "Call", color: "#3b82f6" },
      { id: "t14", name: "Personal", color: "#f97316" },
    ],
    parent: null,
    children: [],
  },
  {
    id: "r-009",
    title: "Push staging deployment",
    description:
      "Coordinate with Rahul after the QA sign-off. Slack him first.",
    due_at: hrsFrom(1),
    completed_at: null,
    snoozed_until: null,
    status: "COMPLETED", // ← completed card — actions hidden, card dimmed
    is_recurring: false,
    recurrence_type: null,
    recurrence_every: null,
    bucket: { name: "Work", icon: "briefcase" },
    tags: [
      { id: "t15", name: "Dev", color: "#10b981" },
      { id: "t16", name: "Deploy", color: "#6366f1" },
    ],
    parent: null,
    children: [],
  },
];
