-- AlterTable
ALTER TABLE "AdminUser" ALTER COLUMN "address_line1" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "address_line2" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "city" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Entity" ALTER COLUMN "name" SET DATA TYPE VARCHAR(120),
ALTER COLUMN "address_line1" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "address_line2" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "city" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "state" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "contact_person" SET DATA TYPE VARCHAR(100);
