// dummyTasks.js - Sample task data for testing

export const dummyTasks = [
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    title: "Complete Q4 Financial Audit Report",
    description: "Prepare comprehensive financial audit for Q4 2024",
    status: "IN_PROGRESS",
    priority: "HIGH",
    due_date: "2025-01-15T10:00:00Z",
    created_at: "2024-12-10T08:30:00Z",
    is_billable: true,
    is_assigned_to_all: false,
    entity: {
      id: "entity-001",
      name: "Acme Corporation Ltd.",
    },
    creator: {
      id: "user-001",
      name: "John Smith",
      email: "john@example.com",
    },
    category: {
      id: "cat-001",
      name: "Financial Audit",
    },
    assignees_preview: [
      { id: "user-001", name: "John Smith" },
      { id: "user-002", name: "Sarah Johnson" },
    ],
    remaining_assignee_count: 0,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    title: "GST Return Filing - December 2024",
    description: "File monthly GST returns for December",
    status: "PENDING",
    priority: "URGENT",
    due_date: "2025-01-08T17:00:00Z",
    created_at: "2025-01-02T09:15:00Z",
    is_billable: true,
    is_assigned_to_all: false,
    entity: {
      id: "entity-002",
      name: "TechStart Solutions Pvt Ltd",
    },
    creator: {
      id: "user-003",
      name: "Priya Sharma",
      email: "priya@example.com",
    },
    category: {
      id: "cat-002",
      name: "Tax Filing",
    },
    assignees_preview: [{ id: "user-003", name: "Priya Sharma" }],
    remaining_assignee_count: 0,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    title: "Annual Compliance Review",
    description: "Review all compliance requirements for the year",
    status: "COMPLETED",
    priority: "NORMAL",
    due_date: "2024-12-31T18:00:00Z",
    created_at: "2024-11-20T11:00:00Z",
    is_billable: false,
    is_assigned_to_all: false,
    entity: {
      id: "entity-003",
      name: "Global Innovations Inc.",
    },
    creator: {
      id: "user-001",
      name: "John Smith",
      email: "john@example.com",
    },
    category: {
      id: "cat-003",
      name: "Compliance",
    },
    assignees_preview: [
      { id: "user-001", name: "John Smith" },
      { id: "user-002", name: "Sarah Johnson" },
      { id: "user-003", name: "Priya Sharma" },
    ],
    remaining_assignee_count: 2,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    title: "Income Tax Assessment - FY 2023-24",
    description: "Prepare income tax assessment for financial year 2023-24",
    status: "ON_HOLD",
    priority: "NORMAL",
    due_date: "2025-01-20T16:00:00Z",
    created_at: "2024-12-15T14:30:00Z",
    is_billable: true,
    is_assigned_to_all: false,
    entity: {
      id: "entity-004",
      name: "Sunshine Retail Group",
    },
    creator: {
      id: "user-002",
      name: "Sarah Johnson",
      email: "sarah@example.com",
    },
    category: {
      id: "cat-002",
      name: "Tax Filing",
    },
    assignees_preview: [],
    remaining_assignee_count: 0,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440005",
    title: "Payroll Processing - January 2025",
    description: "Process monthly payroll for all employees",
    status: "PENDING_CLIENT_INPUT",
    priority: "HIGH",
    due_date: "2025-01-25T12:00:00Z",
    created_at: "2025-01-03T10:00:00Z",
    is_billable: false,
    is_assigned_to_all: true,
    entity: {
      id: "entity-005",
      name: "Metro Manufacturing Ltd",
    },
    creator: {
      id: "user-003",
      name: "Priya Sharma",
      email: "priya@example.com",
    },
    category: {
      id: "cat-004",
      name: "Payroll",
    },
    assignees_preview: [],
    remaining_assignee_count: null,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440006",
    title: "Bank Reconciliation - Q4",
    description: "Reconcile bank statements for Q4 2024",
    status: "IN_PROGRESS",
    priority: "LOW",
    due_date: "2025-02-01T15:00:00Z",
    created_at: "2024-12-28T09:00:00Z",
    is_billable: true,
    is_assigned_to_all: false,
    entity: {
      id: "entity-001",
      name: "Acme Corporation Ltd.",
    },
    creator: {
      id: "user-001",
      name: "John Smith",
      email: "john@example.com",
    },
    category: {
      id: "cat-001",
      name: "Financial Audit",
    },
    assignees_preview: [
      { id: "user-002", name: "Sarah Johnson" },
      { id: "user-004", name: "Rahul Verma" },
    ],
    remaining_assignee_count: 0,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440007",
    title: "TDS Return Preparation",
    description: "Prepare quarterly TDS return",
    status: "CANCELLED",
    priority: "NORMAL",
    due_date: "2025-01-10T11:00:00Z",
    created_at: "2024-12-05T13:20:00Z",
    is_billable: true,
    is_assigned_to_all: false,
    entity: {
      id: "entity-006",
      name: "Digital Marketing Hub",
    },
    creator: {
      id: "user-003",
      name: "Priya Sharma",
      email: "priya@example.com",
    },
    category: {
      id: "cat-002",
      name: "Tax Filing",
    },
    assignees_preview: [{ id: "user-003", name: "Priya Sharma" }],
    remaining_assignee_count: 0,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440008",
    title: "Client Meeting - Annual Financial Review",
    description: "Schedule and conduct annual financial review meeting",
    status: "PENDING",
    priority: "HIGH",
    due_date: "2025-01-09T14:00:00Z",
    created_at: "2025-01-05T08:00:00Z",
    is_billable: false,
    is_assigned_to_all: false,
    entity: null,
    creator: {
      id: "user-002",
      name: "Sarah Johnson",
      email: "sarah@example.com",
    },
    category: null,
    assignees_preview: [
      { id: "user-001", name: "John Smith" },
      { id: "user-002", name: "Sarah Johnson" },
    ],
    remaining_assignee_count: 0,
  },
];
